import { z } from 'zod';
import type { Army, Card, EventCardType, GameState, GeneralCardType, Rules, Unit } from './types';
import { UNIT_TYPES } from './types';

const id = z.string().min(1);

export const GENERAL_CARD_TYPES = ['roll+1', 'roll+2', 'roll-1', 'retreat', 'blockRetreat', 'moves+1'] as const;
export const EVENT_CARD_TYPES = [
  'recruit1', 'recruit2', 'recruitGeneral', 'endGame', 'exhaustion1', 'exhaustion2', 'exhaustion5', 'spies', 'enemySpies', 'sabotage', 'sabotaged', 'nothing',
] as const;

export const DEFAULT_GENERAL_DECK: { card: GeneralCardType; count: number }[] = [
  { card: 'roll+1', count: 10 },
  { card: 'roll+2', count: 10 },
  { card: 'roll-1', count: 10 },
  { card: 'retreat', count: 10 },
  { card: 'blockRetreat', count: 5 },
  { card: 'moves+1', count: 15 },
];

export const DEFAULT_EVENT_DECK: { card: EventCardType; count: number }[] = [
  { card: 'recruit1', count: 6 },
  { card: 'recruit2', count: 3 },
  { card: 'recruitGeneral', count: 3 },
  { card: 'endGame', count: 1 },
  { card: 'exhaustion1', count: 10 },
  { card: 'exhaustion2', count: 5 },
  { card: 'exhaustion5', count: 1 },
  { card: 'spies', count: 5 },
  { card: 'enemySpies', count: 5 },
  { card: 'sabotage', count: 5 },
  { card: 'sabotaged', count: 5 },
  { card: 'nothing', count: 20 },
];

export const DEFAULT_RULES: Rules = { endGameFromRound: 6, mode: 'sides' };

const unitCounts = z.object({
  cavalry: z.number().int().min(0).default(0),
  infantry: z.number().int().min(0).default(0),
  artillery: z.number().int().min(0).default(0),
  supply: z.number().int().min(0).default(0),
});

export const MapConfigSchema = z.object({
  name: z.string(),
  version: z.number().int().default(1),
  /** UI theme: a theme id, or an inline partial theme. Ignored by the rules engine. */
  theme: z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  background: z.string().default('map.png'),
  nodesImage: z.string().default('nodes.png'),
  nations: z.array(z.object({
    id,
    name: z.string(),
    color: z.string(),
    side: z.enum(['attacker', 'defender']),
    threshold: z.number().min(0).max(100).default(50),
    /** Badge shown next to the nation's name; generated by the client when missing. */
    emblem: z.object({
      glyph: z.string().min(1).max(3).optional(),
      shape: z.string().optional(),
      image: z.string().optional(),
    }).optional(),
  })).min(2),
  nodes: z.array(z.object({
    id,
    name: z.string().default(''),
    color: z.string(),
    x: z.number(),
    y: z.number(),
    owner: id,
    controller: id.optional(),
    vp: z.number().int().min(0).default(0),
  })),
  edges: z.array(z.object({ a: id, b: id, type: z.enum(['major', 'minor']).default('minor') })),
  generals: z.array(z.object({ id, name: z.string(), nation: id })).default([]),
  armies: z.array(z.object({
    id,
    nation: id,
    node: id,
    generals: z.array(id).default([]),
    units: unitCounts,
  })).default([]),
  /** Rule options (docs: README "Maps and custom content"). */
  rules: z.object({
    endGameFromRound: z.number().int().min(1).default(DEFAULT_RULES.endGameFromRound),
    mode: z.enum(['sides', 'freeForAll']).default(DEFAULT_RULES.mode),
  }).default(DEFAULT_RULES),
  /**
   * Translations: language code → key → text. Keys are map content ("nation.<id>", "node.<id>",
   * "general.<id>", "map.name") or interface strings (see the client's English dictionary).
   */
  text: z.record(z.string(), z.record(z.string(), z.string())).default({}),
  /** Display names of the languages in `text`, e.g. { "zh": "中文" }. */
  languageNames: z.record(z.string(), z.string()).default({}),
  decks: z.object({
    general: z.array(z.object({ card: z.enum(GENERAL_CARD_TYPES), count: z.number().int().min(0) })),
    event: z.array(z.object({ card: z.enum(EVENT_CARD_TYPES), count: z.number().int().min(0) })),
  }).optional(),
});

export type MapConfig = z.infer<typeof MapConfigSchema>;
export type MapConfigInput = z.input<typeof MapConfigSchema>;

/** Checks references between config entries. Returns a list of problems (empty = valid). */
export function checkConfig(cfg: MapConfig): string[] {
  const problems: string[] = [];
  const nations = new Set(cfg.nations.map((n) => n.id));
  const nodes = new Set<string>();
  for (const n of cfg.nodes) {
    if (nodes.has(n.id)) problems.push(`Duplicate node id "${n.id}"`);
    nodes.add(n.id);
    if (!nations.has(n.owner)) problems.push(`Node "${n.id}" has unknown owner "${n.owner}"`);
    if (n.controller && !nations.has(n.controller)) problems.push(`Node "${n.id}" has unknown controller "${n.controller}"`);
  }
  const degree = new Map<string, number>();
  for (const e of cfg.edges) {
    for (const end of [e.a, e.b]) {
      if (!nodes.has(end)) problems.push(`Edge ${e.a}-${e.b} references unknown node "${end}"`);
      degree.set(end, (degree.get(end) ?? 0) + 1);
    }
    if (e.a === e.b) problems.push(`Edge ${e.a}-${e.b} connects a node to itself`);
  }
  for (const n of cfg.nodes) if (!degree.get(n.id)) problems.push(`Node "${n.id}" has no connections`);
  for (const nat of cfg.nations) {
    if (!cfg.nodes.some((n) => n.owner === nat.id)) problems.push(`Nation "${nat.id}" owns no nodes`);
  }
  if (cfg.rules.mode === 'freeForAll') {
    if (cfg.nations.length < 2) problems.push('A free-for-all game needs at least 2 nations');
  } else {
    if (!cfg.nations.some((n) => n.side === 'attacker')) problems.push('No attacker nation');
    if (!cfg.nations.some((n) => n.side === 'defender')) problems.push('No defender nation');
  }
  const generals = new Map(cfg.generals.map((g) => [g.id, g]));
  const usedGenerals = new Set<string>();
  const armyIds = new Set<string>();
  for (const a of cfg.armies) {
    if (armyIds.has(a.id)) problems.push(`Duplicate army id "${a.id}"`);
    armyIds.add(a.id);
    if (!nations.has(a.nation)) problems.push(`Army "${a.id}" has unknown nation "${a.nation}"`);
    if (!nodes.has(a.node)) problems.push(`Army "${a.id}" is on unknown node "${a.node}"`);
    for (const g of a.generals) {
      const gen = generals.get(g);
      if (!gen) problems.push(`Army "${a.id}" has unknown general "${g}"`);
      else if (gen.nation !== a.nation) problems.push(`General "${g}" does not belong to ${a.nation}`);
      if (usedGenerals.has(g)) problems.push(`General "${g}" is in more than one army`);
      usedGenerals.add(g);
    }
    const units = a.units.cavalry + a.units.infantry + a.units.artillery + a.units.supply;
    if (units + a.generals.length === 0) problems.push(`Army "${a.id}" has no units or generals`);
  }
  return problems;
}

/** Non-fatal issues: the game runs, but the map is probably not what the author intended. */
export function configWarnings(cfg: MapConfig): string[] {
  const warnings: string[] = [];
  const colors = new Map<string, string>();
  for (const n of cfg.nodes) {
    const c = n.color.toLowerCase();
    if (colors.has(c)) warnings.push(`Nodes "${colors.get(c)}" and "${n.id}" share color ${n.color} in the nodes image`);
    colors.set(c, n.id);
    if (!n.name) warnings.push(`Node "${n.id}" has no name`);
  }
  if (!cfg.nodes.some((n) => n.vp > 0)) warnings.push('No node carries victory points');
  return warnings;
}

export function parseConfig(raw: unknown): MapConfig {
  const cfg = MapConfigSchema.parse(raw);
  const problems = checkConfig(cfg);
  if (problems.length) throw new Error(`Invalid map config:\n- ${problems.join('\n- ')}`);
  return cfg;
}

function buildDeck<T extends string>(prefix: string, spec: { card: T; count: number }[]): Card<T>[] {
  const cards: Card<T>[] = [];
  for (const { card, count } of spec) for (let i = 0; i < count; i++) cards.push({ id: `${prefix}${cards.length}`, type: card });
  return cards;
}

export function initialState(cfg: MapConfig): GameState {
  const armies: Record<string, Army> = {};
  for (const a of cfg.armies) {
    const units: Unit[] = [];
    for (const type of UNIT_TYPES) for (let i = 0; i < a.units[type]; i++) units.push({ id: `${a.id}.${type[0]}${i}`, type });
    armies[a.id] = {
      id: a.id,
      nation: a.nation,
      node: a.node,
      generals: [...a.generals],
      units,
      moved: { edges: 0, allMajor: true, bonus: 0, stopped: false },
    };
  }
  return {
    mapName: cfg.name,
    // In a free-for-all game every nation is an attacker.
    nations: cfg.nations.map(({ emblem: _emblem, ...n }) => ({
      ...n, side: cfg.rules.mode === 'freeForAll' ? 'attacker' as const : n.side, warExhaustion: 0, knockedOut: false,
    })),
    nodes: Object.fromEntries(cfg.nodes.map((n) => [n.id, { ...n, controller: n.controller ?? n.owner }])),
    edges: cfg.edges.map((e) => ({ ...e })),
    generals: Object.fromEntries(cfg.generals.map((g) => [g.id, { ...g }])),
    armies,
    // All cards start in the discard pile, so the first draw asks the host for a shuffle.
    generalDeck: { draw: [], discard: buildDeck('g', cfg.decks?.general ?? DEFAULT_GENERAL_DECK) },
    eventDeck: { draw: [], discard: buildDeck('e', cfg.decks?.event ?? DEFAULT_EVENT_DECK) },
    hands: Object.fromEntries(cfg.nations.map((n) => [n.id, []])),
    current: cfg.nations[0].id,
    turn: 1,
    round: 1,
    rules: { ...DEFAULT_RULES, ...cfg.rules },
    phase: 'turnStart',
    turnStart: null,
    turnEnd: null,
    battle: null,
    battleQueue: null,
    pending: [],
    oracle: null,
    reveals: [],
    winner: null,
    nextId: 1,
    history: [],
  };
}
